name: "Robot Test Unlabel"
description: "On new commits, removes the test-robot-done label if present and posts a comment."

inputs:
  label-test-robot-needed:
    description: 'Label indicating the PR needs robot testing'
    required: false
    default: 'test-robot-needed'
  label-test-robot-done:
    description: 'Label indicating the PR has been robot-tested'
    required: false
    default: 'test-robot-done'
  token:
    description: 'GitHub token or PAT used to remove labels and post comments (defaults to github.token)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Remove label and comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token || github.token }}
        script: |
          const labelDone   = '${{ inputs.label-test-robot-done }}';
          const labelNeeded = '${{ inputs.label-test-robot-needed }}';
          const { number: pr, head: { sha } } = context.payload.pull_request;
          const repo = context.repo;

          const postComment = async (body) => {
            try {
              await github.rest.issues.createComment({ ...repo, issue_number: pr, body });
            } catch (err) {
              core.warning(`Could not post comment: ${err.message}`);
            }
          };

          const { data: labels } = await github.rest.issues.listLabelsOnIssue({ ...repo, issue_number: pr });
          const has = new Set(labels.map(l => l.name));

          if (!has.has(labelDone)) {
            core.info(`\`${labelDone}\` not present — nothing to do.`);
            return;
          }

          await github.rest.issues.removeLabel({ ...repo, issue_number: pr, name: labelDone });
          core.info(`\`${labelDone}\` removed.`);

          const shaLine = sha ? `\n\n**Commit:** \`${sha}\`` : '';
          const warning = !has.has(labelNeeded)
            ? `\n\n> [!WARNING]\n> \`${labelDone}\` was removed but \`${labelNeeded}\` was not present — this PR may not be queued for robot testing.`
            : '';

          await postComment(
            `### 🔄 Robot Test Label Removed\n\n` +
            `New commits were pushed. \`${labelDone}\` has been removed and robot testing must be repeated.${shaLine}${warning}`
          );
