name: "Robot Test Check Labels"
description: "Fails if test-robot-needed is present but test-robot-done is not."

inputs:
  label-test-robot-needed:
    description: 'Label indicating the PR needs robot testing'
    required: false
    default: 'test-robot-needed'
  label-test-robot-done:
    description: 'Label indicating the PR has been robot-tested'
    required: false
    default: 'test-robot-done'
  token:
    description: 'GitHub token or PAT used to post comments (defaults to github.token)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Check robot test labels
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token || github.token }}
        script: |
          const labelNeeded = '${{ inputs.label-test-robot-needed }}';
          const labelDone   = '${{ inputs.label-test-robot-done }}';
          const { number: pr, head: { sha } } = context.payload.pull_request;
          const repo = context.repo;

          const postComment = async (body) => {
            try {
              await github.rest.issues.createComment({ ...repo, issue_number: pr, body });
            } catch (err) {
              core.warning(`Could not post comment: ${err.message}`);
            }
          };

          const { data: labels } = await github.rest.issues.listLabelsOnIssue({ ...repo, issue_number: pr });
          const has = new Set(labels.map(l => l.name));

          if (!has.has(labelNeeded)) {
            core.info(`\`${labelNeeded}\` not present — no robot testing required.`);
            return;
          }

          if (has.has(labelDone)) {
            core.info(`\`${labelDone}\` present — robot testing confirmed.`);
            return;
          }

          const shaLine = sha ? `\n\n**Commit:** \`${sha}\`` : '';
          await postComment(
            `### ❌ Robot Testing Required\n\n` +
            `\`${labelNeeded}\` is present but \`${labelDone}\` has not been added. This PR cannot be merged until robot testing is complete.${shaLine}\n\n` +
            `> [!IMPORTANT]\n> Add \`${labelDone}\` once robot testing is complete.`
          );
          core.setFailed(`\`${labelNeeded}\` is present but \`${labelDone}\` has not been added — robot testing must be completed before merging.`);
