name: "Robot Test Label"
description: "When the test-robot-done label is added, posts a comment confirming the robot test status."

inputs:
  label-test-robot-needed:
    description: 'Label indicating the PR needs robot testing'
    required: false
    default: 'test-robot-needed'
  label-test-robot-done:
    description: 'Label indicating the PR has been robot-tested'
    required: false
    default: 'test-robot-done'
  token:
    description: 'GitHub token or PAT used to post comments (defaults to github.token)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Comment on label added
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token || github.token }}
        script: |
          const labelDone   = '${{ inputs.label-test-robot-done }}';
          const labelNeeded = '${{ inputs.label-test-robot-needed }}';
          const { number: pr, head: { sha } } = context.payload.pull_request;
          const repo = context.repo;

          const postComment = async (body) => {
            try {
              await github.rest.issues.createComment({ ...repo, issue_number: pr, body });
            } catch (err) {
              core.warning(`Could not post comment: ${err.message}`);
            }
          };

          const { data: labels } = await github.rest.issues.listLabelsOnIssue({ ...repo, issue_number: pr });
          const has = new Set(labels.map(l => l.name));
          const shaLine = sha ? `\n\n**Commit:** \`${sha}\`` : '';

          if (!has.has(labelDone)) {
            if (has.has(labelNeeded)) {
              core.warning(`\`${labelDone}\` not found. \`${labelNeeded}\` is present but testing is not confirmed.`);
              await postComment(
                `### ⚠️ Robot Testing Incomplete\n\n` +
                `\`${labelNeeded}\` is present but \`${labelDone}\` has not been added yet.${shaLine}\n\n` +
                `> [!WARNING]\n> Add \`${labelDone}\` once robot testing is complete.`
              );
            } else {
              core.info(`\`${labelDone}\` not present. Nothing to do.`);
            }
            return;
          }

          core.info(`\`${labelDone}\` found. Posting confirmation comment.`);
          await postComment(
            `### ✅ Robot Test Complete\n\n` +
            `\`${labelDone}\` has been added. Robot testing has been confirmed for this PR.${shaLine}`
          );
